# Generated by Django 2.1 on 2018-10-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=255)),
                ('phrase', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'base_classification',
            },
        ),
        migrations.CreateModel(
            name='Base_Next',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=255)),
                ('phrase', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'base_next',
            },
        ),
        migrations.CreateModel(
            name='Base_Previous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=255)),
                ('phrase', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'base_previous',
            },
        ),
        migrations.CreateModel(
            name='Base_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=255)),
                ('phrase', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'base_response',
            },
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'corpus',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=255)),
                ('input', models.CharField(max_length=255, unique=True)),
                ('output', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
